### ISSUE TITLE
Graphql query to Fetch data between dates(_Neo4jLocalDateTime),

### ISSUE THREAD

**Issue by jithuprabhakaran** [neo4j-graphql/neo4j-graphql-java#223]
How can we write a Graphql query to fetch data between 2 different dates.? Date property that we use has datatype _Neo4jLocalDateTime.

**Comment by rbramley** [comment]
This is related to #93 - the response states that "_This type of filtering for temporal types is not yet implemented and there is currently no workaround to get it working._"

However, it is possible to workaround it (with an obvious drawback around field selection) by declaring a custom `@cypher` query in your schema e.g. 
```
movieDateFiltered(after: _Neo4jDateInput, before: _Neo4jDateInput): [Movie] @cypher(
statement: "MATCH (m:Movie) WHERE m.pub_date >= date(after) AND m.pub_date <= date(before) RETURN { title: m.title, pub_date: m.pub_date }")
```

And then query as:
```
query { 
  movieDateFiltered(
    after: {year:2016, month:12, day:31},
    before: {year:2020, month:1, day:1}
  )
  {
    title
    pub_date { formatted }
  }
}
```

I've used `_Neo4jDate` for simplicity, but you should be able to extend the same approach for datetimes.

**Comment by jithuprabhakaran** [comment]
Hi Robin Bramley,

Thanks for the response. Let me try like this

Thanks

**Comment by rbramley** [comment]
Hi @jithuprabhakaran, 

If you're on Java 11 and happy to compile a 1.3.1-SNAPSHOT build, I've made a [pull request](https://github.com/neo4j-graphql/neo4j-graphql-java/pull/229) for an initial implementation of date/time filtering. 
As @Andy2003 has pointed out, the `_Neo4jDateInput` type et al will be refactored out as part of the API alignment effort with `neo4j-graphql-js` - so that PR is highly unlikely to be merged.

If you're on Java 8, I've got a variant of that PR that I'm trialling, but it's on a branch created from the 25th March 2021 commit 0f89393884914e906de9d78c1e432b5a09a2ce53 before the update to Neo4j 4.2. I've not yet pushed that to my fork though.
